name: Checks

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  check:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Submodule update
      run: git submodule update --init

    - name: Install lcov
      run: sudo apt -y install lcov

    - name: Build
      run: cmake -H. -Bbuild  -DBUILD_COVERAGE=ON && cmake --build build

    - name: Run tests
      run: cmake --build build --target test --verbose

    - name: Run main
      run: cd build/ && ./task_2 && cd ../

    - name: Build lcov report
      run: cmake --build build --target lcov

    - name: Upload lcov report as artifact
      uses: actions/upload-artifact@v3
      with:
        name: coverage-report
        path: build/lcov/html
        retention-days: 5

    - uses: codecov/codecov-action@v3
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        files: build/lcov/data/capture/all_targets.info
        fail_ci_if_error: true
        verbose: true
